"use client";

import React, { useEffect, useRef, useState } from "react";

export interface ProductionGeneratorProps {
  idea?: string;
  sceneDurations?: number[];
  imageProvider?: string;
  duration?: string | number;
  imagePrompts?: string[];
  videoPrompts?: string[];
  voiceScripts?: string[];
  musicTimeline?: string[];
  sfxPrompts?: string[];
  generatedImages?: string[];
  generatedVideos?: (string | null)[];
  generatedVoiceAudios?: (string | null)[];
  generatedMusicAudios?: (string | null)[];
  generatedSfxAudios?: (string | null)[];

  onImageGenerated?: (
    index: number,
    imageUrl: string
  ) => void;

  onVideoGenerated?: (
    index: number,
    videoUri: string
  ) => void;

  onVoiceGenerated?: (
    index: number,
    audioUrl: string
  ) => void;

  onMusicGenerated?: (
    index: number,
    audioUrl: string
  ) => void;

  onSfxGenerated?: (
    index: number,
    audioUrl: string
  ) => void;

  onGenerationError?: (
    message: string
  ) => void;
}

export default function ProductionGeneratorEngine({
  duration = 30,
  sceneDurations = [],
  imagePrompts = [],
  videoPrompts = [],
  voiceScripts = [],
  generatedImages = [],
  onImageGenerated,
  onGenerationError,
}: ProductionGeneratorProps) {
  const [editableImagePrompts, setEditableImagePrompts] =
    useState<string[]>(imagePrompts);

  const [editableVideoPrompts, setEditableVideoPrompts] =
    useState<string[]>(videoPrompts);

  const [editableVoiceScripts, setEditableVoiceScripts] =
    useState<string[]>(voiceScripts);

  const [generatingImages, setGeneratingImages] =
    useState<boolean[]>([]);

  const [imageErrors, setImageErrors] =
    useState<(string | null)[]>([]);

  /*
   * IMPORTANT:
   * Prevent duplicate image requests caused by React
   * re-renders / StrictMode / changing parent state.
   *
   * Each index is marked before the request starts.
   */
  const imageGenerationStarted =
    useRef<Set<number>>(new Set());

  useEffect(() => {
    setEditableImagePrompts(imagePrompts);
  }, [imagePrompts]);

  useEffect(() => {
    setEditableVideoPrompts(videoPrompts);
  }, [videoPrompts]);

  useEffect(() => {
    setEditableVoiceScripts(voiceScripts);
  }, [voiceScripts]);

  const parsedDuration =
    Number(duration) || 30;

  /*
   * Scene count must come from the actual production
   * data. Image prompts are the primary source because
   * every scene must have one source image.
   */
  const scenesCount = Math.max(
    editableImagePrompts.length,
    editableVideoPrompts.length,
    editableVoiceScripts.length,
    sceneDurations.length
  );

  /*
   * =====================================================
   * IMAGE GENERATION
   * =====================================================
   *
   * The image prompt arriving here is already the final
   * production prompt generated by ImagePromptEngine.
   *
   * Do NOT rebuild or modify the prompt here.
   *
   * This preserves:
   * - selected visual style
   * - character locks
   * - scene action
   * - environment
   * - camera
   * - lighting
   * - continuity
   */

  useEffect(() => {
    let cancelled = false;

    const generateMissingImages = async () => {
      for (
        let index = 0;
        index < editableImagePrompts.length;
        index++
      ) {
        if (cancelled) return;

        const prompt =
          editableImagePrompts[index]?.trim();

        if (!prompt) {
          console.warn(
            `⚠️ Scene ${index + 1}: image prompt is empty.`
          );
          continue;
        }

        /*
         * Existing generated image:
         * NEVER regenerate it.
         */
        if (generatedImages[index]) {
          continue;
        }

        /*
         * Already requested during this production:
         * NEVER send another request.
         */
        if (
          imageGenerationStarted.current.has(
            index
          )
        ) {
          continue;
        }

        /*
         * Mark BEFORE fetch to prevent duplicate
         * requests from concurrent renders.
         */
        imageGenerationStarted.current.add(
          index
        );

        setGeneratingImages((current) => {
          const updated = [...current];
          updated[index] = true;
          return updated;
        });

        setImageErrors((current) => {
          const updated = [...current];
          updated[index] = null;
          return updated;
        });

        console.log(
          `🖼️ Generating production image ${index + 1}/${editableImagePrompts.length}...`
        );

        console.log(
          `📝 Scene ${index + 1} prompt length: ${prompt.length}`
        );

        try {
          const response = await fetch(
            "/api/generate-image",
            {
              method: "POST",
              headers: {
                "Content-Type":
                  "application/json",
              },
              body: JSON.stringify({
                prompt,
                provider:
                  "cloudflare",
              }),
            }
          );

          const result =
            await response.json();

          if (
            !response.ok ||
            !result.success
          ) {
            throw new Error(
              result.message ||
                `Image generation failed for Scene ${
                  index + 1
                }.`
            );
          }

          const imageUrl =
            result.imageUrl ||
            result.image ||
            "";

          if (!imageUrl) {
            throw new Error(
              `Scene ${
                index + 1
              }: Cloudflare returned no image.`
            );
          }

          if (cancelled) return;

          console.log(
            `✅ Scene ${index + 1} image generated successfully.`
          );

          onImageGenerated?.(
            index,
            imageUrl
          );

          setGeneratingImages(
            (current) => {
              const updated = [
                ...current,
              ];

              updated[index] =
                false;

              return updated;
            }
          );
        } catch (error) {
          if (cancelled) return;

          const message =
            error instanceof Error
              ? error.message
              : `Scene ${
                  index + 1
                }: image generation failed.`;

          console.error(
            `❌ Scene ${index + 1} image generation failed:`,
            message
          );

          setImageErrors(
            (current) => {
              const updated = [
                ...current,
              ];

              updated[index] =
                message;

              return updated;
            }
          );

          setGeneratingImages(
            (current) => {
              const updated = [
                ...current,
              ];

              updated[index] =
                false;

              return updated;
            }
          );

          onGenerationError?.(
            message
          );

          /*
           * Do NOT automatically retry.
           *
           * Automatic retries can waste provider
           * quota when the failure is quota/rate-limit
           * related.
           */
          return;
        }
      }
    };

    void generateMissingImages();

    return () => {
      cancelled = true;
    };
  }, [
    editableImagePrompts,
    generatedImages,
    onImageGenerated,
    onGenerationError,
  ]);

  const generatedImageCount =
    generatedImages.filter(
      Boolean
    ).length;

  const allImagesReady =
    editableImagePrompts.length > 0 &&
    editableImagePrompts.every(
      (_, index) =>
        Boolean(
          generatedImages[index]
        )
    );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between border-b border-white/10 pb-3">
        <div>
          <h3 className="flex items-center gap-2 text-base font-bold text-white">
            🎬 Production Generator Engine
          </h3>

          <p className="text-xs text-gray-400">
            Autonomous multi-modal
            orchestration engine in live
            production.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs font-mono text-cyan-400">
          <span>
            ⏱️ Total: {parsedDuration}s
          </span>

          <span>•</span>

          <span>
            🎞️ {scenesCount} Scenes
          </span>

          <span>•</span>

          <span>
            🖼️ {generatedImageCount}/
            {editableImagePrompts.length}
          </span>
        </div>
      </div>

      {allImagesReady && (
        <div className="rounded-xl border border-emerald-400/20 bg-emerald-400/5 p-4 text-sm text-emerald-300">
          ✅ All source images are ready.
          Video generation can now use these
          exact saved source images.
        </div>
      )}

      <div className="space-y-6">
        {Array.from({
          length: scenesCount,
        }).map((_, index) => {
          const currentImage =
            generatedImages[index];

          const isGenerating =
            Boolean(
              generatingImages[index]
            );

          const error =
            imageErrors[index];

          return (
            <div
              key={index}
              className="rounded-2xl border border-white/10 bg-black/40 p-4 transition-all"
            >
              <div className="mb-3 flex items-center justify-between border-b border-white/5 pb-2">
                <span className="text-sm font-bold text-cyan-300">
                  🎬 Scene {index + 1}
                </span>

                <span className="text-xs font-mono text-gray-400">
                  {sceneDurations[
                    index
                  ] ?? 5}
                  s
                </span>
              </div>

              <div className="grid grid-cols-1 gap-4 md:grid-cols-12">
                {/* =================================================
                    SOURCE IMAGE
                    ================================================= */}

                <div className="relative flex min-h-[260px] items-center justify-center overflow-hidden rounded-xl border border-white/10 bg-black/60 md:col-span-5">
                  {currentImage ? (
                    <img
                      src={currentImage}
                      alt={`Scene ${
                        index + 1
                      }`}
                      className="aspect-[9/16] h-full w-full rounded-lg object-cover"
                    />
                  ) : isGenerating ? (
                    <div className="flex flex-col items-center justify-center space-y-3 p-6 text-center">
                      <div className="h-8 w-8 animate-spin rounded-full border-2 border-cyan-400 border-t-transparent" />

                      <span className="text-xs font-semibold text-gray-400">
                        Generating source
                        image...
                      </span>

                      <span className="text-[10px] text-gray-500">
                        Cloudflare FLUX
                      </span>
                    </div>
                  ) : error ? (
                    <div className="p-6 text-center">
                      <div className="mb-2 text-2xl">
                        ❌
                      </div>

                      <p className="text-xs text-red-400">
                        {error}
                      </p>
                    </div>
                  ) : (
                    <div className="flex flex-col items-center justify-center p-6 text-center">
                      <div className="mb-2 text-2xl">
                        ⏳
                      </div>

                      <span className="text-xs text-gray-500">
                        Waiting for image
                        generation...
                      </span>
                    </div>
                  )}
                </div>

                {/* =================================================
                    DIRECTIVES & SCRIPT OUTPUTS
                    ================================================= */}

                <div className="space-y-3 md:col-span-7">
                  <div>
                    <label className="mb-1 flex items-center gap-1 text-[11px] font-bold text-amber-400">
                      🎨 Image Prompt
                    </label>

                    <textarea
                      readOnly
                      rows={5}
                      value={
                        editableImagePrompts[
                          index
                        ] || ""
                      }
                      className="w-full resize-none rounded-lg border border-white/10 bg-black/50 p-2 text-xs font-mono text-gray-300 focus:outline-none"
                    />
                  </div>

                  <div>
                    <label className="mb-1 flex items-center gap-1 text-[11px] font-bold text-purple-400">
                      🎥 Video Motion Prompt
                    </label>

                    <textarea
                      readOnly
                      rows={5}
                      value={
                        editableVideoPrompts[
                          index
                        ] || ""
                      }
                      className="w-full resize-none rounded-lg border border-white/10 bg-black/50 p-2 text-xs font-mono text-gray-300 focus:outline-none"
                    />
                  </div>

                  <div>
                    <label className="mb-1 flex items-center gap-1 text-[11px] font-bold text-emerald-400">
                      🎙️ Voiceover Script
                    </label>

                    <textarea
                      readOnly
                      rows={3}
                      value={
                        editableVoiceScripts[
                          index
                        ] || ""
                      }
                      className="w-full resize-none rounded-lg border border-white/10 bg-black/50 p-2 text-xs text-gray-200 focus:outline-none"
                    />
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}